### PR TITLE
Settings > Access Control

### PR DESCRIPTION
**Pull request by diamond-darrell**
- support the expandable arrow for data-table (styling),
- set style for multiselect,
- extend autocomplete component to support validators
- implement time-spinner component

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kaltura-ng/68)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 10 of 10 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[kaltura-primeng-ui/src/auto-complete/auto-complete.component.ts, line 486 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/68#-L4p4ask2M4pXEgHwYxS:-L4p4ask2M4pXEgHwYxT:b-74vv2h) ([raw file](https://github.com/kaltura/kaltura-ng/blob/017980f275b632ddf122edd22e229127bec2b252/kaltura-primeng-ui/src/auto-complete/auto-complete.component.ts#L486)):*
> ```XML
>     }
>     
>     public _validateItem(item: any) : boolean {
> ```

I'm not sure if the performance here fits.... because it will happen alot of times. just add a console log, and move the mouse in a view that holds that component with at least one item inside it

maybe instead of extending this component, use the existing api of the component. use `classField` input to map to a field that will hold the 'invalid class name' together with `onItemAdding` input to validate that field

wdyt?



---

*[kaltura-primeng-ui/src/styles/scss/theme.scss, line 70 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/68#-L4p5Ur2OoAysv8YMZBm:-L4p5Ur2OoAysv8YMZBn:b-1k3ur1) ([raw file](https://github.com/kaltura/kaltura-ng/blob/017980f275b632ddf122edd22e229127bec2b252/kaltura-primeng-ui/src/styles/scss/theme.scss#L70)):*
> ```SCSS
>         }
>       }
>       &.userAdded{
> ```

did you add this on purpose? because we removed it a month ago

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/68)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[kaltura-primeng-ui/src/auto-complete/auto-complete.component.ts, line 486 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/68#-L4p4ask2M4pXEgHwYxS:-L4p7TYEI8amMCuOpN0M:b3nlu9k) ([raw file](https://github.com/kaltura/kaltura-ng/blob/017980f275b632ddf122edd22e229127bec2b252/kaltura-primeng-ui/src/auto-complete/auto-complete.component.ts#L486)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

I'm not sure if the performance here fits.... because it will happen alot of times. just add a console log, and move the mouse in a view that holds that component with at least one item inside it

maybe instead of extending this component, use the existing api of the component. use `classField` input to map to a field that will hold the 'invalid class name' together with `onItemAdding` input to validate that field

wdyt?



</blockquote></details>

not sure how can I determine needed dom element in `onItemAdding`

---

*[kaltura-primeng-ui/src/styles/scss/theme.scss, line 70 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/68#-L4p5Ur2OoAysv8YMZBm:-L4p6mIOu2x7r6yYwL3a:bbj0aoa) ([raw file](https://github.com/kaltura/kaltura-ng/blob/017980f275b632ddf122edd22e229127bec2b252/kaltura-primeng-ui/src/styles/scss/theme.scss#L70)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

did you add this on purpose? because we removed it a month ago
</blockquote></details>

I'm added only invalid state, `userAdded` class was here before me
here's the commit where I did changes  - https://github.com/kaltura/kaltura-ng/commit/cb33e2ebc0f0481f34081b93112a40999d6f7e6c

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/68)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[kaltura-primeng-ui/src/styles/scss/theme.scss, line 70 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/68#-L4p5Ur2OoAysv8YMZBm:-L5DRzkr5uQc4wQZSDdz:b-457tfn) ([raw file](https://github.com/kaltura/kaltura-ng/blob/017980f275b632ddf122edd22e229127bec2b252/kaltura-primeng-ui/src/styles/scss/theme.scss#L70)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

I'm added only invalid state, `userAdded` class was here before me
here's the commit where I did changes  - https://github.com/kaltura/kaltura-ng/commit/cb33e2ebc0f0481f34081b93112a40999d6f7e6c
</blockquote></details>

I think it's still needed


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/68)*

**Comment by diamond-darrell** [comment]
Review status: 6 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[kaltura-primeng-ui/src/auto-complete/auto-complete.component.ts, line 486 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/68#-L4p4ask2M4pXEgHwYxS:-L5n3meYrHbmjVJDL3h3:bb7f2mf) ([raw file](https://github.com/kaltura/kaltura-ng/blob/017980f275b632ddf122edd22e229127bec2b252/kaltura-primeng-ui/src/auto-complete/auto-complete.component.ts#L486)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

not sure how can I determine needed dom element in `onItemAdding`
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/68)*

**Comment by esakal** [comment]
Reviewed 3 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[kaltura-primeng-ui/src/styles/scss/theme.scss, line 70 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/68#-L4p5Ur2OoAysv8YMZBm:-L4p98Xp7R0G3m6w9oap:b-xtq5cm) ([raw file](https://github.com/kaltura/kaltura-ng/blob/017980f275b632ddf122edd22e229127bec2b252/kaltura-primeng-ui/src/styles/scss/theme.scss#L70)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

I think it's still needed


</blockquote></details>

the code snippet is in the application (kmc-ng) so the style should be taken from there (using the /deep/ techinque) - you can remove it from here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/68)*

**Comment by diamond-darrell** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[kaltura-primeng-ui/src/styles/scss/theme.scss, line 70 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/68#-L4p5Ur2OoAysv8YMZBm:-L5nJG5TwhYdamt2YBKd:b32w0x) ([raw file](https://github.com/kaltura/kaltura-ng/blob/017980f275b632ddf122edd22e229127bec2b252/kaltura-primeng-ui/src/styles/scss/theme.scss#L70)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

the code snippet is in the application (kmc-ng) so the style should be taken from there (using the /deep/ techinque) - you can remove it from here
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/68)*

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/68)*

**Pull request merged**
