### PR TITLE
Add clearable input

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [] Bugfix
- [x] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**
Add a component wrapper for input to support clear button option inside a text input.

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kaltura-ng/116)

### CODE REVIEW

**Comment by esakal** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @diamond-darrell, @amirch1, and @esakal)

---

*[kaltura-primeng-ui/src/clearable-input/clearable-input.component.ts, line 5 at r1](https://reviewable.io/reviews/kaltura/kaltura-ng/116#-LFziayxC2Gw_2bjhekR:-LFziayyEncNXH91zv4L:b-pti46t) ([raw file](https://github.com/kaltura/kaltura-ng/blob/59ddc030f2e3ff425073cd4ea231d8d402a383da/kaltura-primeng-ui/src/clearable-input/clearable-input.component.ts#L5)):*
> ```XML
> import { DomHandler } from 'primeng/primeng';
> 
> export const SPINNER_VALUE_ACCESSOR: any = {
> ```

is the name correct? shouldn't it be `CLEARABLE_INPUT_VALUE_ACCESSOR`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kaltura-ng/116#-:-LFzj3ks3YmWz2PgUFSD:bnfp4nl)*

**Comment by esakal** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @diamond-darrell and @amirch1)

---



*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kaltura-ng/116)*

**Comment by amirch1** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed, 2 unresolved discussions (waiting on @diamond-darrell)

---

*[a discussion](https://reviewable.io/reviews/kaltura/kaltura-ng/116#-LFzliPR-oSsp6Ki8f3I:-LFzliPR-oSsp6Ki8f3J:b8vvxvx) (no related file):*
It would be better if the X icon appears only after the user hit the enter key meaning a search term is currently applied. Currently it appears the minute the user starts typing

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kaltura-ng/116)*

**Comment by diamond-darrell** [comment]
Review status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @amirch1 and @esakal)

---

*[a discussion](https://reviewable.io/reviews/kaltura/kaltura-ng/116#-LFzliPR-oSsp6Ki8f3I:-LFzwxXs-pjkmbaxu5Gc:b32w0x) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

It would be better if the X icon appears only after the user hit the enter key meaning a search term is currently applied. Currently it appears the minute the user starts typing
</blockquote></details>

OK

---

*[kaltura-primeng-ui/src/clearable-input/clearable-input.component.ts, line 5 at r1](https://reviewable.io/reviews/kaltura/kaltura-ng/116#-LFziayxC2Gw_2bjhekR:-LFzwwSx3Dup3uiyokNT:b32w0x) ([raw file](https://github.com/kaltura/kaltura-ng/blob/59ddc030f2e3ff425073cd4ea231d8d402a383da/kaltura-primeng-ui/src/clearable-input/clearable-input.component.ts#L5)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

is the name correct? shouldn't it be `CLEARABLE_INPUT_VALUE_ACCESSOR`?
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kaltura-ng/116)*

**Comment by diamond-darrell** [comment]
Review status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @amirch1 and @esakal)

---

*[a discussion](https://reviewable.io/reviews/kaltura/kaltura-ng/116#-LFzliPR-oSsp6Ki8f3I:-LFzz6BOD9r7ForO1C11:bw1echm) (no related file):*
<details><summary><i>Previously, diamond-darrell (Stas Kohut) wrote…</i></summary><blockquote>

OK
</blockquote></details>

Once a user removes all content from the input they need to press enter to clear the input (or press clear input button). Is this okay? Or we need to support also hiding the clear button if a user blurs the input with no value in it?

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kaltura-ng/116)*

**Comment by amirch1** [comment]
Review status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @amirch1 and @esakal)

---

*[a discussion](https://reviewable.io/reviews/kaltura/kaltura-ng/116#-LFzliPR-oSsp6Ki8f3I:-LFzzqE9-O_RD2EtL7zx:b-produ5) (no related file):*
<details><summary><i>Previously, diamond-darrell (Stas Kohut) wrote…</i></summary><blockquote>

Once a user removes all content from the input they need to press enter to clear the input (or press clear input button). Is this okay? Or we need to support also hiding the clear button if a user blurs the input with no value in it?
</blockquote></details>

this is fine

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kaltura-ng/116)*

**Comment by diamond-darrell** [comment]
Review status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @amirch1 and @esakal)

---

*[a discussion](https://reviewable.io/reviews/kaltura/kaltura-ng/116#-LFzliPR-oSsp6Ki8f3I:-LG--05XE3fO_Bdnual2:b32w0x) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

this is fine
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kaltura-ng/116)*

**Comment by esakal** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kaltura-ng/116#-:-LG-2eFPA9sIVwxyYAyJ:bnfp4nl)*

**Pull request merged**
