### PR TITLE
feat: Prepare audio, video, and live entries

### PR DESCRIPTION
**Pull request by benstov**
added ip & url validators

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kaltura-ng/16)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/16)*

**Comment by amirch1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kaltura-ng/16#-KvzXiyRrmsniVJIuxbQ:-KvzXiyRrmsniVJIuxbR:bjwqyy8) (no related file):*
+@esakal - do you think that kaltura-ui is the correct project for the validators? Maybe kaltura-common? These validators are not UI specific.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/16)*

**Comment by esakal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kaltura-ng/16#-KvzXiyRrmsniVJIuxbQ:-KvzulHk6VTgNfXXN5lH:b-m5dlr4) (no related file):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

+@esakal - do you think that kaltura-ui is the correct project for the validators? Maybe kaltura-common? These validators are not UI specific.
</blockquote></details>

Let's keep it in the kaltura-ui so we won't create a dependency between the common library to `@angular/forms`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/16)*

**Comment by esakal** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/16#-:-Kvzv98TRBetwQcSJIVo:bnfp4nl)*

**Comment by amirch1** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/16#-:-KvzvMe5UWNJdYyxKwfJ:bnfp4nl)*

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/16)*

**Pull request merged**
