### PR TITLE
KMCNG-1792

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
https://kaltura.atlassian.net/browse/KMCNG-1792

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kaltura-ng/113)

### CODE REVIEW

**Comment by diamond-darrell** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[kaltura-ui/src/validators/validators.ts, line 4 at r1](https://reviewable.io/reviews/kaltura/kaltura-ng/113#-LDk3cSvBG_IEz3dDSBb:-LDk3cSvBG_IEz3dDSBc:bus75ic) ([raw file](https://github.com/kaltura/kaltura-ng/blob/1515230a7e69f73d0013587323d76ed08be936ee/kaltura-ui/src/validators/validators.ts#L4)):*
> ```XML
> 
> // accepts http/https/ftp
> export const urlRegex = new RegExp("(ftp|https?):\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%_\\+.~#?&//=]*)","i");
> ```

+@esakal 
1. pattern was taken from here https://stackoverflow.com/a/3809435/4312928
2. double escaping thing - it's required if you use `RegExp` constructor and providing a pattern as a string
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#Description


---


*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kaltura-ng/113)*

**Comment by esakal** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kaltura-ng/113#-:-LDkKic04JmaJ_CDaJ7-:bnfp4nl)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kaltura-ng/113)*

**Comment by amirch1** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/kaltura/kaltura-ng/113#-:-LDkKzAIE59z-7qsMBBA:bnfp4nl)*

**Pull request merged**
