### PR TITLE
Playlists adjustments

### PR DESCRIPTION
**Pull request by esakal**
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kaltura-ng/29)

### CODE REVIEW

**Comment by diamond-darrell** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/29#-:-KyGWqhpH_aZ5pY-PjeP:bnfp4nl)*

**Comment by diamond-darrell** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/29)*

**Comment by diamond-darrell** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/29)*

**Comment by amirch1** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/29#-:-Kyyh-dVBn4yoysbrf-U:bnfp4nl)*

**Pull request merged**
