### PR TITLE
feat: modify tooltip position when dragging the target component

### PR DESCRIPTION
**Pull request by diamond-darrell**
---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kaltura-ng/49)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[kaltura-primeng-ui/src/slider/slider.component.ts, line 16 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/49#-L-zkTdSX36qHcslP7RB:-L-zkTdSX36qHcslP7RC:b-2qdik3) ([raw file](https://github.com/kaltura/kaltura-ng/blob/4eba23a0b87a96bb2785da9be65c9d0303260c00/kaltura-primeng-ui/src/slider/slider.component.ts#L16)):*
> ```XML
> 
> @Component({
>   selector: 'kSlider',
> ```

I'm not sure but I think html tag names should be lower case with hyphens.

---

*[kaltura-ui/src/tooltip/k-tooltip.directive.ts, line 39 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/49#-L-zpucIa842vmbhMowM:-L-zpucIa842vmbhMowN:bhbormj) ([raw file](https://github.com/kaltura/kaltura-ng/blob/4eba23a0b87a96bb2785da9be65c9d0303260c00/kaltura-ui/src/tooltip/k-tooltip.directive.ts#L39)):*
> ```XML
>   @HostListener("mousemove") moveTooltip() {
>     if (this.followTarget && this._tooltip) {
>       if (this.escape) {
> ```

you implemented two different requirements in the same place.
this function should only invoke `setPosition()` is currently showing tooltip and `followTarget` is enabled.

the part of updating `_tooltip` content should move to a setter function of `kTooltip` property so everytime someone updates the value, if the tooltip is currently shown, should update its content immediately as you did here.

contact me if needed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/49)*

**Comment by diamond-darrell** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[kaltura-primeng-ui/src/slider/slider.component.ts, line 16 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/49#-L-zkTdSX36qHcslP7RB:-L03ZxoluBKEGoSgTIgO:bwcqxbs) ([raw file](https://github.com/kaltura/kaltura-ng/blob/4eba23a0b87a96bb2785da9be65c9d0303260c00/kaltura-primeng-ui/src/slider/slider.component.ts#L16)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

I'm not sure but I think html tag names should be lower case with hyphens.
</blockquote></details>

yes, and IDE highlights it as an error, but in other places, we mostly name selectors in this way, so I've decided make it the same with others (kAutoComplete, kPopupWidget). However, along with those names, we have also other that follows angular recommendations (k-area-blocker, k-prime-control, etc). We probably should do something with this situation and use only one approach to make it solid

---

*[kaltura-ui/src/tooltip/k-tooltip.directive.ts, line 39 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/49#-L-zpucIa842vmbhMowM:-L0441043ndRPjpGW6cb:b32w0x) ([raw file](https://github.com/kaltura/kaltura-ng/blob/4eba23a0b87a96bb2785da9be65c9d0303260c00/kaltura-ui/src/tooltip/k-tooltip.directive.ts#L39)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

you implemented two different requirements in the same place.
this function should only invoke `setPosition()` is currently showing tooltip and `followTarget` is enabled.

the part of updating `_tooltip` content should move to a setter function of `kTooltip` property so everytime someone updates the value, if the tooltip is currently shown, should update its content immediately as you did here.

contact me if needed
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/49)*

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/49)*

**Comment by esakal** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/49#-:-L1NNg8A33IYk1Uyy3VP:bnfp4nl)*

**Comment by esakal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kaltura-ng/49#-L1fniIFvsiRHIZlg4Nx:-L1fniIFvsiRHIZlg4Ny:b-b3c06u) (no related file):*
should test sliders as part of playlist rule-based testing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/49)*

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/49)*

**Pull request merged**
