### PR TITLE
KMCNG-941

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [] Bugfix
- [x] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
https://kaltura.atlassian.net/browse/KMCNG-941

**What is the new behavior?**
allow pass input to the directive

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kaltura-ng/82)

### CODE REVIEW

**Comment by esakal** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kaltura-ng/82#-L4WSJ5DC9GHrcHSppcF:-L4WSJ5DC9GHrcHSppcG:beccliu) (no related file):*
+@amirch1 please provide your insights

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/82)*

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/82)*

**Comment by amirch1** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/82#-:-L4e_3jps8MRt610ooYf:bnfp4nl)*

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[kaltura-primeng-ui/src/directives/menu-close-on-scroll.ts, line 10 at r2](https://reviewable.io:443/reviews/kaltura/kaltura-ng/82#-L4kvffpkcI7wyMPjVRe:-L4kvffpkcI7wyMPjVRf:bdgyde3) ([raw file](https://github.com/kaltura/kaltura-ng/blob/abd9e318f21b66c1326d49c184d98d29d03e5672/kaltura-primeng-ui/src/directives/menu-close-on-scroll.ts#L10)):*
> ```XML
> 	private  _menu: Menu | TieredMenu;
> 
> 	constructor(@Optional() menu: Menu, @Optional() tieredMenu: TieredMenu)
> ```

+@diamond-darrell I think getting the element we attached to the directive in the constructor is a bit more cleaner approach. This way we don't need to 'ask' the user to bind itself (tiered menu) into the directive.

wdyt?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/82)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[kaltura-primeng-ui/src/directives/menu-close-on-scroll.ts, line 10 at r2](https://reviewable.io:443/reviews/kaltura/kaltura-ng/82#-L4kvffpkcI7wyMPjVRe:-L4kyKDdGaQ5twbGIId9:b-8fx2u7) ([raw file](https://github.com/kaltura/kaltura-ng/blob/abd9e318f21b66c1326d49c184d98d29d03e5672/kaltura-primeng-ui/src/directives/menu-close-on-scroll.ts#L10)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

+@diamond-darrell I think getting the element we attached to the directive in the constructor is a bit more cleaner approach. This way we don't need to 'ask' the user to bind itself (tiered menu) into the directive.

wdyt?
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/82)*

**Pull request merged**
