### PR TITLE
Upload settings

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kaltura-ng/4)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 9 of 10 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-Ksb6gZgw_cFRbjkKKN5:-Ksb6gZhu9xF_yH457vV:buo43uj) (no related file):*
Hi, I think you can update the status of [KMCNG-547](https://kaltura.atlassian.net/browse/KMCNG-547) to ready for code review.  if not what is needed to complete it?

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-Ksch0eh_2SN2LhCQipB:-Ksch0eh_2SN2LhCQipC:bnmplx9) (no related file):*
BTW I would like to separate the commits to the master between the upload changes and the autofocus directive. Hopefully I will remember it :)

---

*[kaltura-common/src/upload-management/upload-management.service.ts, line 76 at r2](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-Ks_OPDUa__SK1QbliiR:-Ks_OPDUa__SK1QbliiS:b-d57ttk) ([raw file](https://github.com/kaltura/kaltura-ng/blob/91a83762fc523b429180de13085de6cb293307a5/kaltura-common/src/upload-management/upload-management.service.ts#L76)):*
> ```XML
> 
>         if (isSubscription) {
>             uploadSubscription.unsubscribe();
> ```

consider deleting the `uploadToken` from `_uploadingFileSubscriptions` since you just cancelled it. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4)*

**Comment by diamond-darrell** [comment]
Review status: 10 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-Ksb6gZgw_cFRbjkKKN5:-Ksd5N8bprpaKTYiJ9M5:b-zde4xd) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

Hi, I think you can update the status of [KMCNG-547](https://kaltura.atlassian.net/browse/KMCNG-547) to ready for code review.  if not what is needed to complete it?
</blockquote></details>

But I haven't implemented the second part of story yet
`Clicking the "View Details" link in the "Upload Monitor" screen`

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-Ksch0eh_2SN2LhCQipB:-Ksd5Z5ODlP7yl08WYab:b-6lh05g) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

BTW I would like to separate the commits to the master between the upload changes and the autofocus directive. Hopefully I will remember it :)
</blockquote></details>

Do I need to create another branch and move implementation there? What do I need to do with changes in upload-settings branch?

---

*[kaltura-common/src/upload-management/upload-management.service.ts, line 76 at r2](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-Ks_OPDUa__SK1QbliiR:-Ksd5vNjY0BYXvX-9JRD:b-xjwlet) ([raw file](https://github.com/kaltura/kaltura-ng/blob/91a83762fc523b429180de13085de6cb293307a5/kaltura-common/src/upload-management/upload-management.service.ts#L76)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

consider deleting the `uploadToken` from `_uploadingFileSubscriptions` since you just cancelled it. 
</blockquote></details>

Will you do it as part of queueing or I have to do it now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4)*

**Comment by esakal** [comment]
Reviewed 1 of 10 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-Ksb6gZgw_cFRbjkKKN5:-KsheXt60EXOs8XBY6Nx:bksc994) (no related file):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

But I haven't implemented the second part of story yet
`Clicking the "View Details" link in the "Upload Monitor" screen`
</blockquote></details>

I assumed this is the reason :) I think its fine because it is already covered in 'Upload Monitor' PRD requirement `Allow drill-down for each upload source` so you will not miss it when you will implement it there.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-Ksch0eh_2SN2LhCQipB:-KshfF3riN3qD4jjCWXM:b-uzltkj) (no related file):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

Do I need to create another branch and move implementation there? What do I need to do with changes in upload-settings branch?
</blockquote></details>

Nope, I think I will rebase before I will squash it to master, you don't need to do anything 

---

*[kaltura-common/src/upload-management/upload-management.service.ts, line 76 at r2](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-Ks_OPDUa__SK1QbliiR:-Kshg3mQIEUCFq-wZrIC:b-lfp91u) ([raw file](https://github.com/kaltura/kaltura-ng/blob/91a83762fc523b429180de13085de6cb293307a5/kaltura-common/src/upload-management/upload-management.service.ts#L76)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

Will you do it as part of queueing or I have to do it now?
</blockquote></details>

FYI I will do it. (I started the comment with FYI so it will be resolved automatically)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4)*

**Comment by diamond-darrell** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-Ksb6gZgw_cFRbjkKKN5:-KshraEU87tnQ9u4Mqer:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

I assumed this is the reason :) I think its fine because it is already covered in 'Upload Monitor' PRD requirement `Allow drill-down for each upload source` so you will not miss it when you will implement it there.
</blockquote></details>

OK

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-Ksch0eh_2SN2LhCQipB:-KshrcU_Oqk7-8c7IYUf:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

Nope, I think I will rebase before I will squash it to master, you don't need to do anything 
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4)*

**Comment by diamond-darrell** [comment]
Review status: 7 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[kaltura-common/src/upload-management/upload-management.service.ts, line 13 at r7](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-Ku3KnN4fPMWcewMnN9T:-Ku3KnN4fPMWcewMnN9U:b3cewd8) ([raw file](https://github.com/kaltura/kaltura-ng/blob/5dbd0efa625d7594a2e243b26ba15e8a2ae6bbcc/kaltura-common/src/upload-management/upload-management.service.ts#L13)):*
> ```XML
> {
>     uploadToken: string,
>     status : "uploading" | "uploaded" | "uploadFailure" | "pending" | "cancelled" | "removed",
> ```

+@esakal maybe we should extract the status type to a dedicated type declaration because it's used the same type inside kmc-ng app and we need to change them in both places when refactoring. 

---

*[kaltura-common/src/upload-management/upload-management.service.ts, line 193 at r7](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-Ku3Rg-FBu6RfOd2lqrL:-Ku3Rg-FBu6RfOd2lqrM:bzdpp8o) ([raw file](https://github.com/kaltura/kaltura-ng/blob/5dbd0efa625d7594a2e243b26ba15e8a2ae6bbcc/kaltura-common/src/upload-management/upload-management.service.ts#L193)):*
> ```XML
>     private _updateTrackedFile(trackedFile : TrackedFile, changes : Partial<TrackedFile>) : void;
>     private _updateTrackedFile(uploadToken : string, changes : Partial<TrackedFile>) : void;
>     private _updateTrackedFile(target : TrackedFile | string, changes : Partial<TrackedFile>) : void {
> ```

+@esakal I'm just wondering - what is the profit of this way of function declaration, I mean you still have to declare both types in function with a body :slightly_smiling_face: 

---

*[kaltura-server-utils/src/upload-management/kaltura-upload.ts, line 103 at r7](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-Ku3Pb_VpsBsS2fUhlHv:-Ku3Pb_VpsBsS2fUhlHw:bxm9lcm) ([raw file](https://github.com/kaltura/kaltura-ng/blob/5dbd0efa625d7594a2e243b26ba15e8a2ae6bbcc/kaltura-server-utils/src/upload-management/kaltura-upload.ts#L103)):*
> ```XML
>                                         this._log('info',`got (server) upload token '${serverUploadToken}' for file with (client) upload token '${uploadToken}'`);
> 
>                                         uploadFile.serverUploadToken = serverUploadToken;
> ```

+@esakal why do you update serverUploadToken in uploadFile, it's used in the code below?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4)*

**Comment by diamond-darrell** [comment]
Review status: 4 of 19 files reviewed at latest revision, 5 unresolved discussions.

---

*[kaltura-common/src/upload-management/upload-management.service.ts, line 13 at r7](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-Ku3KnN4fPMWcewMnN9T:-KuZQzDBuMPuPk9azIkb:b32w0x) ([raw file](https://github.com/kaltura/kaltura-ng/blob/5dbd0efa625d7594a2e243b26ba15e8a2ae6bbcc/kaltura-common/src/upload-management/upload-management.service.ts#L13)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

+@esakal maybe we should extract the status type to a dedicated type declaration because it's used the same type inside kmc-ng app and we need to change them in both places when refactoring. 
</blockquote></details>

OK

---

*[kaltura-common/src/upload-management/upload-management.service.ts, line 193 at r7](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-Ku3Rg-FBu6RfOd2lqrL:-KuZQqWyYVG74SLLuiPM:b32w0x) ([raw file](https://github.com/kaltura/kaltura-ng/blob/5dbd0efa625d7594a2e243b26ba15e8a2ae6bbcc/kaltura-common/src/upload-management/upload-management.service.ts#L193)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

+@esakal I'm just wondering - what is the profit of this way of function declaration, I mean you still have to declare both types in function with a body :slightly_smiling_face: 
</blockquote></details>

OK

---

*[kaltura-common/src/upload-management/upload-management.service.ts, line 13 at r9](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-KuZOCZG49i66nGuJvtG:-KuZOCZG49i66nGuJvtH:b3e0nrq) ([raw file](https://github.com/kaltura/kaltura-ng/blob/f6ab9d32f88c223133babab48f46321cd5ace7b2/kaltura-common/src/upload-management/upload-management.service.ts#L13)):*
> ```XML
> export type TrackedFileStatus = string
> 
> export class TrackedFileStatuses {
> ```

+@esakal I wanted to make TrackedFilesStatuses an enum, but there were a couple of issues:
1) if I declare enum without values (ts automatically assigns numbers) then it's not informative in log output because instead of names of statuses it shows numbers
2) I can't assign string values to enum (like enum TrackedFilesStatuses { added = "added" ... }) because it's not allowed by ts
So, I decided to make a class with static props. I considered it as a good approach because we have IDE's autocompletion on statuses and we can easily rename any property with automatic renaming in all places of the project.
I would like to know your opinion on that.

---

*[kaltura-common/src/upload-management/upload-management.service.ts, line 198 at r9](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-KuZPnOOIvL3A4TaMgog:-KuZPnOOIvL3A4TaMgoh:bkdpfem) ([raw file](https://github.com/kaltura/kaltura-ng/blob/f6ab9d32f88c223133babab48f46321cd5ace7b2/kaltura-common/src/upload-management/upload-management.service.ts#L198)):*
> ```XML
>     }
> 
>     public setMediaEntryId(trackedFile: TrackedFile, entryId: string): void {
> ```

+@esakal I've added `mediaCreated` status and public method `setMediaEntryId` to add ability update entryId for table and cancellation operations (because they require entryId). I didn't come up with a better solution, and I also would like to see what do you think of this way of setting entryId. 
Also, I need to restore the previous status because if a file has `waitingUpload` status it doesn't start to upload when there will be an available slot for upload.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4)*

**Comment by esakal** [comment]
Reviewed 1 of 10 files at r1, 1 of 3 files at r5, 2 of 5 files at r6, 9 of 10 files at r8, 4 of 4 files at r9.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[kaltura-common/src/upload-management/upload-management.service.ts, line 193 at r7](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-Ku3Rg-FBu6RfOd2lqrL:-KumtVA7DoVw0tk9sp_n:b-xyb9e3) ([raw file](https://github.com/kaltura/kaltura-ng/blob/5dbd0efa625d7594a2e243b26ba15e8a2ae6bbcc/kaltura-common/src/upload-management/upload-management.service.ts#L193)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

OK
</blockquote></details>

FYI, The developer will see in the IDE intellisense that he should provide a string representing the id or the actual tracked file instance.

I could use only the 3rd declaration but then the user will need to figure out that the string represent and id :)

---

*[kaltura-common/src/upload-management/upload-management.service.ts, line 13 at r9](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-KuZOCZG49i66nGuJvtG:-KumlqrpwUYHmyCh3E1E:bqq3s3i) ([raw file](https://github.com/kaltura/kaltura-ng/blob/f6ab9d32f88c223133babab48f46321cd5ace7b2/kaltura-common/src/upload-management/upload-management.service.ts#L13)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

+@esakal I wanted to make TrackedFilesStatuses an enum, but there were a couple of issues:
1) if I declare enum without values (ts automatically assigns numbers) then it's not informative in log output because instead of names of statuses it shows numbers
2) I can't assign string values to enum (like enum TrackedFilesStatuses { added = "added" ... }) because it's not allowed by ts
So, I decided to make a class with static props. I considered it as a good approach because we have IDE's autocompletion on statuses and we can easily rename any property with automatic renaming in all places of the project.
I would like to know your opinion on that.
</blockquote></details>

FYI, Good thinking! many people forget to the affect of enum on the log messages.

enum as a string is a new feature introduced in [typescript 2.4](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-4.html). We need to upgrade angular-cli first and then typescript to enjoy this feature. We have a pending task for that due next week. 

Let's use this implementation until we will upgrade typescript and then you will be able to do a small refactoring to utilize the enum string for that purpose.

---

*[kaltura-common/src/upload-management/upload-management.service.ts, line 17 at r9](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-Kump-2M_0lCepzVqvYy:-Kump-2M_0lCepzVqvYz:b-osxhp6) ([raw file](https://github.com/kaltura/kaltura-ng/blob/f6ab9d32f88c223133babab48f46321cd5ace7b2/kaltura-common/src/upload-management/upload-management.service.ts#L17)):*
> ```XML
>   public static readonly preparing: TrackedFileStatus = 'preparing';
>   public static readonly waitingUpload: TrackedFileStatus = 'waitingUpload';
>   public static readonly mediaCreated: TrackedFileStatus = 'mediaCreated';
> ```

see my other comments on entry upload inside the core logic

---

*[kaltura-common/src/upload-management/upload-management.service.ts, line 28 at r9](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-KumnqktiJfUXTsbvyEd:-KumnqkuwwBJK4fTHJ7U:b-2al2x2) ([raw file](https://github.com/kaltura/kaltura-ng/blob/f6ab9d32f88c223133babab48f46321cd5ace7b2/kaltura-common/src/upload-management/upload-management.service.ts#L28)):*
> ```XML
>     id: string,
>     status: TrackedFileStatus,
>     entryId?: string;
> ```

The upload management is kaltura-ng serves many purposes not necessarily related to entries.

For that purpose you should use the dedicated class overriding the uploaded file data to provide entry related properties like `entryId`, `mediaType` and `transcoding profile id` - see it in [github NewEntryUploadFile file](https://github.com/kaltura/kmc-ng/blob/bb23616f0e2023e8e8df3f6fb1defff4e4fc5971/src/shared/kmc-shell/new-entry-upload/new-entry-upload-file.ts#L5)

---

*[kaltura-common/src/upload-management/upload-management.service.ts, line 198 at r9](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-KuZPnOOIvL3A4TaMgog:-Kump66kLQpmZUE1Dgvm:b-nxyp1b) ([raw file](https://github.com/kaltura/kaltura-ng/blob/f6ab9d32f88c223133babab48f46321cd5ace7b2/kaltura-common/src/upload-management/upload-management.service.ts#L198)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

+@esakal I've added `mediaCreated` status and public method `setMediaEntryId` to add ability update entryId for table and cancellation operations (because they require entryId). I didn't come up with a better solution, and I also would like to see what do you think of this way of setting entryId. 
Also, I need to restore the previous status because if a file has `waitingUpload` status it doesn't start to upload when there will be an available slot for upload.
</blockquote></details>

Following my comment about the `entryId`. I think it should be part of the `NewEntryUploadFile` which is responsible for entries upload process and is part of the application. 

Having this logic in the infrastructure couple the entry upload to the core upload.

Let's discuss

---

*[kaltura-common/src/upload-management/upload-management.service.ts, line 215 at r9](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-KumqDEDcbbCfrCLibR6:-KumqDEDcbbCfrCLibR7:b-h0ek2n) ([raw file](https://github.com/kaltura/kaltura-ng/blob/f6ab9d32f88c223133babab48f46321cd5ace7b2/kaltura-common/src/upload-management/upload-management.service.ts#L215)):*
> ```XML
>         // should be null, so this is a cleanup function just in case.
>         const trackedFileUploadData = this._trackedFilesUploadData[id];
>         if (trackedFileUploadData && trackedFileUploadData.uploadSubscription) {
> ```

I saw you added here an extra check. Usually I'm in favor of protective programming but I'm curious, did you encountered a scenario where it was undefined? if so how to reproduce it?

---

*[kaltura-common/src/upload-management/upload-management.service.ts, line 536 at r9](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-KumszRAsw07Y9hUvGl5:-KumszRAsw07Y9hUvGl6:bj9fs40) ([raw file](https://github.com/kaltura/kaltura-ng/blob/f6ab9d32f88c223133babab48f46321cd5ace7b2/kaltura-common/src/upload-management/upload-management.service.ts#L536)):*
> ```XML
> 
>     ngOnDestroy(): void {
>         console.warn('ngOnDestroy', this._trackedFilesUploadData);
> ```

cleanup?

If you left this on purpose since you think this is needed to debug in the future the use the `_log` instead of `console.log` and change the level to `debug` (because it is not a problem we need to warn about)

---

*[kaltura-server-utils/src/upload-management/kaltura-upload.ts, line 103 at r7](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-Ku3Pb_VpsBsS2fUhlHv:-Kumu6_kmHs23WPfSq4R:bn2y3s) ([raw file](https://github.com/kaltura/kaltura-ng/blob/5dbd0efa625d7594a2e243b26ba15e8a2ae6bbcc/kaltura-server-utils/src/upload-management/kaltura-upload.ts#L103)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

+@esakal why do you update serverUploadToken in uploadFile, it's used in the code below?
</blockquote></details>

Is this comment still relevant? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[kaltura-common/src/upload-management/upload-management.service.ts, line 193 at r7](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-Ku3Rg-FBu6RfOd2lqrL:-Kumvn3Q_Hwoq1xe43Fl:b32w0x) ([raw file](https://github.com/kaltura/kaltura-ng/blob/5dbd0efa625d7594a2e243b26ba15e8a2ae6bbcc/kaltura-common/src/upload-management/upload-management.service.ts#L193)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

FYI, The developer will see in the IDE intellisense that he should provide a string representing the id or the actual tracked file instance.

I could use only the 3rd declaration but then the user will need to figure out that the string represent and id :)
</blockquote></details>

OK

---

*[kaltura-common/src/upload-management/upload-management.service.ts, line 13 at r9](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-KuZOCZG49i66nGuJvtG:-KumvTDf_cGKPy7BbXyp:b32w0x) ([raw file](https://github.com/kaltura/kaltura-ng/blob/f6ab9d32f88c223133babab48f46321cd5ace7b2/kaltura-common/src/upload-management/upload-management.service.ts#L13)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

FYI, Good thinking! many people forget to the affect of enum on the log messages.

enum as a string is a new feature introduced in [typescript 2.4](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-4.html). We need to upgrade angular-cli first and then typescript to enjoy this feature. We have a pending task for that due next week. 

Let's use this implementation until we will upgrade typescript and then you will be able to do a small refactoring to utilize the enum string for that purpose.
</blockquote></details>

OK

---

*[kaltura-common/src/upload-management/upload-management.service.ts, line 17 at r9](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-Kump-2M_0lCepzVqvYy:-KumvZ8JHVon4GBEAZQg:b32w0x) ([raw file](https://github.com/kaltura/kaltura-ng/blob/f6ab9d32f88c223133babab48f46321cd5ace7b2/kaltura-common/src/upload-management/upload-management.service.ts#L17)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

see my other comments on entry upload inside the core logic
</blockquote></details>

OK

---

*[kaltura-common/src/upload-management/upload-management.service.ts, line 28 at r9](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-KumnqktiJfUXTsbvyEd:-KumwbcUloMMDMQBmMPm:b-l80fyb) ([raw file](https://github.com/kaltura/kaltura-ng/blob/f6ab9d32f88c223133babab48f46321cd5ace7b2/kaltura-common/src/upload-management/upload-management.service.ts#L28)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

The upload management is kaltura-ng serves many purposes not necessarily related to entries.

For that purpose you should use the dedicated class overriding the uploaded file data to provide entry related properties like `entryId`, `mediaType` and `transcoding profile id` - see it in [github NewEntryUploadFile file](https://github.com/kaltura/kmc-ng/blob/bb23616f0e2023e8e8df3f6fb1defff4e4fc5971/src/shared/kmc-shell/new-entry-upload/new-entry-upload-file.ts#L5)
</blockquote></details>

yes, that makes sense, it relates to my question below

---

*[kaltura-common/src/upload-management/upload-management.service.ts, line 198 at r9](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-KuZPnOOIvL3A4TaMgog:-Kumwo0VS3GBW4xbGYP8:b-7v0p2o) ([raw file](https://github.com/kaltura/kaltura-ng/blob/f6ab9d32f88c223133babab48f46321cd5ace7b2/kaltura-common/src/upload-management/upload-management.service.ts#L198)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

Following my comment about the `entryId`. I think it should be part of the `NewEntryUploadFile` which is responsible for entries upload process and is part of the application. 

Having this logic in the infrastructure couple the entry upload to the core upload.

Let's discuss
</blockquote></details>

Let's :slightly_smiling_face: 
Since I need to display entryId in the upload table and listen to onFileStatusChanged$ directly from uploadManagement service I needed to somehow get entryId and the only way I had seen was to add new status and listen to it inside list component. However,  I agree that it should be moved to entry related code.
Maybe I should add this logic to the NewEntryUploadService and listen `mediaCreated` from here? 

---

*[kaltura-common/src/upload-management/upload-management.service.ts, line 215 at r9](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-KumqDEDcbbCfrCLibR6:-Kumw4iwObhQD6RUpUMn:b-8bgh2s) ([raw file](https://github.com/kaltura/kaltura-ng/blob/f6ab9d32f88c223133babab48f46321cd5ace7b2/kaltura-common/src/upload-management/upload-management.service.ts#L215)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

I saw you added here an extra check. Usually I'm in favor of protective programming but I'm curious, did you encountered a scenario where it was undefined? if so how to reproduce it?
</blockquote></details>

I can't provide you a stable way to reproduce it, but sometimes when you cancel upload this line causes `property on undefined` type of error, so I've added this extra check

---

*[kaltura-common/src/upload-management/upload-management.service.ts, line 536 at r9](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-KumszRAsw07Y9hUvGl5:-KumvrS-j4NMBh1CJS3c:b-jedolz) ([raw file](https://github.com/kaltura/kaltura-ng/blob/f6ab9d32f88c223133babab48f46321cd5ace7b2/kaltura-common/src/upload-management/upload-management.service.ts#L536)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

cleanup?

If you left this on purpose since you think this is needed to debug in the future the use the `_log` instead of `console.log` and change the level to `debug` (because it is not a problem we need to warn about)
</blockquote></details>

yes, cleanup, thanks, I didn't notice it's still there
OK

---

*[kaltura-server-utils/src/upload-management/kaltura-upload.ts, line 103 at r7](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-Ku3Pb_VpsBsS2fUhlHv:-Kumw-db-gZAcxAJJfPv:b-7m559c) ([raw file](https://github.com/kaltura/kaltura-ng/blob/5dbd0efa625d7594a2e243b26ba15e8a2ae6bbcc/kaltura-server-utils/src/upload-management/kaltura-upload.ts#L103)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

Is this comment still relevant? 
</blockquote></details>

no
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4)*

**Comment by esakal** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[kaltura-server-utils/src/transcoding-profile-management/transcoding-profile-management.service.ts, line 30 at r9](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-KunG-61DzVrrCWD3B65:-KunG-61DzVrrCWD3B66:bf52p3i) ([raw file](https://github.com/kaltura/kaltura-ng/blob/f6ab9d32f88c223133babab48f46321cd5ace7b2/kaltura-server-utils/src/transcoding-profile-management/transcoding-profile-management.service.ts#L30)):*
> ```XML
>   }
> 
>   public get(cache = true): Observable<KalturaConversionProfile[]> {
> ```

remove the cache api because it should be handled by services that will call `clearCache` once needed

---

*[kaltura-server-utils/src/transcoding-profile-management/transcoding-profile-management.service.ts, line 36 at r9](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-Kun68a6EqpoJ_1t-xwi:-Kun68a6EqpoJ_1t-xwj:b-qygdw4) ([raw file](https://github.com/kaltura/kaltura-ng/blob/f6ab9d32f88c223133babab48f46321cd5ace7b2/kaltura-server-utils/src/transcoding-profile-management/transcoding-profile-management.service.ts#L36)):*
> ```XML
> 
>     if (!this._trancodingProfileCache$) {
>       this._trancodingProfileCache$ = this._loadTrancsodingProfiles()
> ```

How do you handle load transcoding failures? I think this [line](https://github.com/kaltura/kmc-ng/blob/184c8c911a81267c1dc5425fd3714ff906bcb18b/src/applications/kmc-upload-app/upload-settings/upload-settings.component.ts#L160) will always return a failure.

Obviously you can clear the cache from the component but I think you should consider internal logic (using `catch` operator)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[kaltura-server-utils/src/transcoding-profile-management/transcoding-profile-management.service.ts, line 30 at r9](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-KunG-61DzVrrCWD3B65:-KunGULBnctXnYtFEZET:b32w0x) ([raw file](https://github.com/kaltura/kaltura-ng/blob/f6ab9d32f88c223133babab48f46321cd5ace7b2/kaltura-server-utils/src/transcoding-profile-management/transcoding-profile-management.service.ts#L30)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

remove the cache api because it should be handled by services that will call `clearCache` once needed
</blockquote></details>

OK

---

*[kaltura-server-utils/src/transcoding-profile-management/transcoding-profile-management.service.ts, line 36 at r9](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4#-Kun68a6EqpoJ_1t-xwi:-KunGjAIMBCUAlBv-j-d:b32w0x) ([raw file](https://github.com/kaltura/kaltura-ng/blob/f6ab9d32f88c223133babab48f46321cd5ace7b2/kaltura-server-utils/src/transcoding-profile-management/transcoding-profile-management.service.ts#L36)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

How do you handle load transcoding failures? I think this [line](https://github.com/kaltura/kmc-ng/blob/184c8c911a81267c1dc5425fd3714ff906bcb18b/src/applications/kmc-upload-app/upload-settings/upload-settings.component.ts#L160) will always return a failure.

Obviously you can clear the cache from the component but I think you should consider internal logic (using `catch` operator)


</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4)*

**Comment by esakal** [comment]
Reviewed 2 of 2 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/4)*

**Pull request merged**
