### PR TITLE
KMCNG-562

### PR DESCRIPTION
**Pull request by diamond-darrell**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kaltura-ng/48)

### CODE REVIEW

**Comment by esakal** [comment]
It seems that your provided solution doesn't meet the requirements, it should:
1. always prevent duplicate values even if the user type them with different casing (prevent the user from sending both `AnGuLAR` and `angular`)
2. if the user didn't added duplicated values, don't manipulate its' text. if the user typed `AnGuLAR` it should be sent to the server using the same casing.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/48#-:-L-QAwuJRsk0ArUzWlUZ:b-v3it03)*

**Comment by esakal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kaltura-ng/48#-L-QDqmSiFqblBikt-el:-L-QDqmSiFqblBikt-em:b-f9y2mu) (no related file):*
It seems that your provided solution doesn't meet the requirements, it should:

always prevent duplicate values even if the user type them with different casing (prevent the user from sending both AnGuLAR and angular)
if the user didn't added duplicated values, don't manipulate its' text. if the user typed AnGuLAR it should be sent to the server using the same casing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/48)*

**Comment by amirch1** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/48#-:-L-_t2JkWC-qjeTCiQoa:bnfp4nl)*

**Comment by esakal** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/48#-:-L-_tBdoeotA-uLWp0Qn:bnfp4nl)*

**Pull request merged**
