### PR TITLE
fix: fix loading spinner layout

### PR DESCRIPTION
**Pull request by amirch1**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kaltura-ng/47)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kaltura-ng/47#-L-RtudQmxMp_THX6PM7:-L-RtudQmxMp_THX6PM8:b-so3k2d) (no related file):*
shouldn't  this be handled?



---

*[kaltura-ui/src/area-blocker/area-blocker.component.scss, line 8 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/47#-L-RtWwn-knfby33PQk1:-L-RtWwn-knfby33PQk2:bijslfs) ([raw file](https://github.com/kaltura/kaltura-ng/blob/95d2f5291c7bc62852146140a734fdeb022199e0/kaltura-ui/src/area-blocker/area-blocker.component.scss#L8)):*
> ```SCSS
> 	flex: 1 1 auto;
> 	> .kAreaBlockerContainer {
> 		display: flex;
> ```

since KEA is working with kaltura-ui area blocker, didn't we move any flex related styles to the theme? Since I understand it might be not reasonable to do it here, you need to consider having this feature enabled only to any browser not IE11.

Let's discuss

---

*[kaltura-ui/src/area-blocker/area-blocker.component.ts, line 26 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/47#-L-RuMdz22piP1V-cT8q:-L-RuMdz22piP1V-cT8r:b-m3kdxj) ([raw file](https://github.com/kaltura/kaltura-ng/blob/95d2f5291c7bc62852146140a734fdeb022199e0/kaltura-ui/src/area-blocker/area-blocker.component.ts#L26)):*
> ```XML
>     if (value){
>       setTimeout(()=>{
>         if (this.centerOnScreen && this.areaBlockerContainer){
> ```

are there situations where 'areaBlockerContainer' not exists?

---

*[kaltura-ui/src/area-blocker/area-blocker.component.ts, line 28 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/47#-L-RugF4skF0OA1t3SST:-L-RugF4skF0OA1t3SSU:b-vf77rv) ([raw file](https://github.com/kaltura/kaltura-ng/blob/95d2f5291c7bc62852146140a734fdeb022199e0/kaltura-ui/src/area-blocker/area-blocker.component.ts#L28)):*
> ```XML
>         if (this.centerOnScreen && this.areaBlockerContainer){
>           const rect = this.areaBlockerContainer.nativeElement.getBoundingClientRect();
>           if (rect.width < document.body.clientWidth && this.spinnerContainer){
> ```

are there situations where 'spinnerContainer' not exists?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/47)*

**Comment by amirch1** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kaltura-ng/47#-L-RtudQmxMp_THX6PM7:-L-_FVXNbLdecaiHAqY9:b-vrgpef) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

shouldn't  this be handled?


</blockquote></details>

can't load the gif...can't load the gif... :(

---

*[kaltura-ui/src/area-blocker/area-blocker.component.scss, line 8 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/47#-L-RtWwn-knfby33PQk1:-L-_FqcP6fgP3TQddx7S:b-6euo5x) ([raw file](https://github.com/kaltura/kaltura-ng/blob/95d2f5291c7bc62852146140a734fdeb022199e0/kaltura-ui/src/area-blocker/area-blocker.component.scss#L8)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

since KEA is working with kaltura-ui area blocker, didn't we move any flex related styles to the theme? Since I understand it might be not reasonable to do it here, you need to consider having this feature enabled only to any browser not IE11.

Let's discuss
</blockquote></details>

Its not our responsibility to test and provide support for IE10. We develop for IE11 and up. If KIA needs support for IE10 - they can easily override this class in their own theme and make it compatible with IE10.

---

*[kaltura-ui/src/area-blocker/area-blocker.component.ts, line 26 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/47#-L-RuMdz22piP1V-cT8q:-L-_GCKxKQJeqwKJQ07x:b8fe891) ([raw file](https://github.com/kaltura/kaltura-ng/blob/95d2f5291c7bc62852146140a734fdeb022199e0/kaltura-ui/src/area-blocker/area-blocker.component.ts#L26)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

are there situations where 'areaBlockerContainer' not exists?
</blockquote></details>

Yes, as it has *ngIF on it.

---

*[kaltura-ui/src/area-blocker/area-blocker.component.ts, line 28 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/47#-L-RugF4skF0OA1t3SST:-L-_GGooFzrhjgHWG91T:bvsisp2) ([raw file](https://github.com/kaltura/kaltura-ng/blob/95d2f5291c7bc62852146140a734fdeb022199e0/kaltura-ui/src/area-blocker/area-blocker.component.ts#L28)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

are there situations where 'spinnerContainer' not exists?
</blockquote></details>

Yes, as it is wrapped with a div with *ngIf on it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/47)*

**Comment by esakal** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/47)*

**Comment by esakal** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/47#-:-L-aWoHGLVsYM7Vk5GoA:bnfp4nl)*

**Pull request merged**
