### PR TITLE
dynamic from control and validations and switch control type

### PR DESCRIPTION
**Pull request by tanyaLibatter**
* add switch control type in prime-control
* add validators to dynamic form control
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [] Bugfix
- [X] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kaltura-ng/52)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kaltura-ng/52#-L1E0PLuezaJw1bszPy2:-L1E0PLuezaJw1bszPy3:b-5ndezh) (no related file):*
A general question: when a validation failed, does your change show a visual notification so the user will know what is needed to be fixed?

---

*[kaltura-ui/src/dynamic-form/dynamic-form-item.component.ts, line 18 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/52#-L1E0-lFUaMUFPQPWip7:-L1E0-lFUaMUFPQPWip8:b-vsdvms) ([raw file](https://github.com/kaltura/kaltura-ng/blob/c87e07622f2ddb8d7c69b927aa2d83f2ffab4cce/kaltura-ui/src/dynamic-form/dynamic-form-item.component.ts#L18)):*
> ```XML
>     @ContentChildren(TemplateRef, {descendants: false}) public _templates: QueryList<TemplateRef<any>>;
> 
>     public get isRequired(): boolean {
> ```

consider calculating that value in advance in the constructor or during onInit to improve performance (doing it in getter property will cause this function to execute it self every dirty check.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/52)*

**Comment by tanyaLibatter** [comment]
Review status: 4 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kaltura-ng/52#-L1E0PLuezaJw1bszPy2:-L1IE6Iqc8tACvKdbfTM:bdywa30) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

A general question: when a validation failed, does your change show a visual notification so the user will know what is needed to be fixed?
</blockquote></details>

Done. Added an error mapping and container to display a field error

---

*[kaltura-ui/src/dynamic-form/dynamic-form-item.component.ts, line 18 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/52#-L1E0-lFUaMUFPQPWip7:-L1IEOq-dBVkWYD0aUa2:bb6un1j) ([raw file](https://github.com/kaltura/kaltura-ng/blob/c87e07622f2ddb8d7c69b927aa2d83f2ffab4cce/kaltura-ui/src/dynamic-form/dynamic-form-item.component.ts#L18)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

consider calculating that value in advance in the constructor or during onInit to improve performance (doing it in getter property will cause this function to execute it self every dirty check.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/52)*

**Comment by esakal** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[kaltura-primeng-ui/src/dynamic-form/prime-control.component.ts, line 22 at r2](https://reviewable.io:443/reviews/kaltura/kaltura-ng/52#-L1Ic3p1VnTYpytx_blx:-L1Ic3p1VnTYpytx_bly:b-jdu4gu) ([raw file](https://github.com/kaltura/kaltura-ng/blob/1a43d3bda99cadf7471100cb220ac4af9d2fee6d/kaltura-primeng-ui/src/dynamic-form/prime-control.component.ts#L22)):*
> ```XML
>         if(this.control.errors){
>             const BreakException = {};
>             try {
> ```

what is your goal here? if you want to get the first relevant error then using a try...catch has performance hit and is a bit complex for that purpose. 

consider using `.find()` here as-well. also note that I added support for generic fallback message if user didn't provided errors mapping or a message to a specific one
```
let result = '';

const formControl = this.form.controls[this.control.key];
if (this.control.errors && !formControl.valid)
{
   const firstErrorKey = Object.keys(this.control.errors).find( errorKey => 
   formControl.hasError(errorKey)); 

   if (firstErrorKey)
   {
       result = this.control.errors[firstErrorKey];
   }
}

return result || 'set here a generic fallback error message';
```

---

*[kaltura-ui/src/dynamic-form/dynamic-form-item.component.ts, line 31 at r2](https://reviewable.io:443/reviews/kaltura/kaltura-ng/52#-L1I_WfjY7rDx_kULL-M:-L1I_WfjY7rDx_kULL-N:b-1smyby) ([raw file](https://github.com/kaltura/kaltura-ng/blob/1a43d3bda99cadf7471100cb220ac4af9d2fee6d/kaltura-ui/src/dynamic-form/dynamic-form-item.component.ts#L31)):*
> ```XML
>                 .filter(validator => {
>                     return validator == Validators.required;
>                 })[0] ;
> ```

did you try this? I think you will get an error if none of the validators is `Validators.required`. Are you familiar with `.find()` operator, I think this is more suitable to our need.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/52)*

**Comment by tanyaLibatter** [comment]
Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[kaltura-primeng-ui/src/dynamic-form/prime-control.component.ts, line 22 at r2](https://reviewable.io:443/reviews/kaltura/kaltura-ng/52#-L1Ic3p1VnTYpytx_blx:-L1Ikx3-SPq_dIayF8pf:b-3h16sq) ([raw file](https://github.com/kaltura/kaltura-ng/blob/1a43d3bda99cadf7471100cb220ac4af9d2fee6d/kaltura-primeng-ui/src/dynamic-form/prime-control.component.ts#L22)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

what is your goal here? if you want to get the first relevant error then using a try...catch has performance hit and is a bit complex for that purpose. 

consider using `.find()` here as-well. also note that I added support for generic fallback message if user didn't provided errors mapping or a message to a specific one
```
let result = '';

const formControl = this.form.controls[this.control.key];
if (this.control.errors && !formControl.valid)
{
   const firstErrorKey = Object.keys(this.control.errors).find( errorKey => 
   formControl.hasError(errorKey)); 

   if (firstErrorKey)
   {
       result = this.control.errors[firstErrorKey];
   }
}

return result || 'set here a generic fallback error message';
```
</blockquote></details>

That is exactly my purpose, I was not familiar with find operator this is why I din't use it...
I added a generic fallback message but I don't think you right  about this one - we might want have only field highlight in some validations without a detailed message below

---

*[kaltura-ui/src/dynamic-form/dynamic-form-item.component.ts, line 31 at r2](https://reviewable.io:443/reviews/kaltura/kaltura-ng/52#-L1I_WfjY7rDx_kULL-M:-L1Ilp17S7-MgRkhTKMo:bur2a6h) ([raw file](https://github.com/kaltura/kaltura-ng/blob/1a43d3bda99cadf7471100cb220ac4af9d2fee6d/kaltura-ui/src/dynamic-form/dynamic-form-item.component.ts#L31)):*
>  
As I mentioned before I wasn't familiar with .find() operator  (I'm now :-) ) and yes it didn't throw any error because thank to this if:
  if(requeredValidator)
                this.isRequired=true;
anyway I changed the implementation and now I'm using find 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/52)*

**Comment by esakal** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[kaltura-primeng-ui/src/dynamic-form/prime-control.component.ts, line 22 at r2](https://reviewable.io:443/reviews/kaltura/kaltura-ng/52#-L1Ic3p1VnTYpytx_blx:-L1J1i1cy7vBEpqBEQt1:b-cck54c) ([raw file](https://github.com/kaltura/kaltura-ng/blob/1a43d3bda99cadf7471100cb220ac4af9d2fee6d/kaltura-primeng-ui/src/dynamic-form/prime-control.component.ts#L22)):*
<details><summary><i>Previously, tanyaLibatter (Tanya Libatter) wrote…</i></summary><blockquote>

That is exactly my purpose, I was not familiar with find operator this is why I din't use it...
I added a generic fallback message but I don't think you right  about this one - we might want have only field highlight in some validations without a detailed message below
</blockquote></details>

OK, we can remove the fallback message, the reason I thought you don't plan to support empty message is that you still show the div>span element without any content meaning the user will see a jump without any reason.

so we have two choices:
1. leave the fallback message. which as you said might not fit all scenarios and also doesn't support translation in the current implementation.
2. show the error message only if there is one. This one will require you to change the way you get that message otherwise you will have two places bound to a function instead of a property (which affect performance). We can discuss about it tomorrow

---

*[kaltura-ui/src/dynamic-form/dynamic-form-item.component.ts, line 31 at r2](https://reviewable.io:443/reviews/kaltura/kaltura-ng/52#-L1I_WfjY7rDx_kULL-M:-L1J1Vda7tgCKHmVokKU:b5a94l5) ([raw file](https://github.com/kaltura/kaltura-ng/blob/1a43d3bda99cadf7471100cb220ac4af9d2fee6d/kaltura-ui/src/dynamic-form/dynamic-form-item.component.ts#L31)):*
<details><summary><i>Previously, tanyaLibatter (Tanya Libatter) wrote…</i></summary><blockquote>

>  
As I mentioned before I wasn't familiar with .find() operator  (I'm now :-) ) and yes it didn't throw any error because thank to this if:
  if(requeredValidator)
                this.isRequired=true;
anyway I changed the implementation and now I'm using find 
</blockquote></details>

OK, actually I mean the the `filter(...)[0]` will throw an error if there isn't any validator of type required. 

but you fix now should work so no need to change anything.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/52)*

**Comment by tanyaLibatter** [comment]
Review status: 8 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[kaltura-primeng-ui/src/dynamic-form/prime-control.component.ts, line 22 at r2](https://reviewable.io:443/reviews/kaltura/kaltura-ng/52#-L1Ic3p1VnTYpytx_blx:-L1M7pskecOV7k8MaQlu:b-9kkx3l) ([raw file](https://github.com/kaltura/kaltura-ng/blob/1a43d3bda99cadf7471100cb220ac4af9d2fee6d/kaltura-primeng-ui/src/dynamic-form/prime-control.component.ts#L22)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

OK, we can remove the fallback message, the reason I thought you don't plan to support empty message is that you still show the div>span element without any content meaning the user will see a jump without any reason.

so we have two choices:
1. leave the fallback message. which as you said might not fit all scenarios and also doesn't support translation in the current implementation.
2. show the error message only if there is one. This one will require you to change the way you get that message otherwise you will have two places bound to a function instead of a property (which affect performance). We can discuss about it tomorrow
</blockquote></details>

I implemented option number 2 - getting the error message on form statusChanges and only if form is invalid invalid  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/52)*

**Comment by esakal** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/52#-:-L1MQJWG6s1yr1m_094r:bnfp4nl)*

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/52)*

**Pull request merged**
