### PR TITLE
feat: New scroll system and screen layouts

### PR DESCRIPTION
**Pull request by amirch1**
### PR information
**What kind of change does this PR introduce?** (check one with "x")
- [] Bugfix
- [] Feature
- [] Code style update (formatting, local variables)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] CI related changes
- [] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [] Yes
- [] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

---

### Other information

**Where should the reviewer start?**

**How should this be manually tested?**

**Any background context you want to provide?**

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kaltura-ng/22)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[kaltura-primeng-ui/src/directives/sticky-datatable-header.directive.ts, line 6 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/22#-Kwj3WEhxnGD_GS9tBG2:-Kwj3WEhxnGD_GS9tBG3:bs9sxi4) ([raw file](https://github.com/kaltura/kaltura-ng/blob/c7a6a55f26820e1f0eab771353840e4824ad9d24/kaltura-primeng-ui/src/directives/sticky-datatable-header.directive.ts#L6)):*
> ```XML
> 
> @Directive({
>     selector: '[stickyHeader]'
> ```

`k` prefix.... you can ignore if you don't have the power to change everywhere 

---

*[kaltura-primeng-ui/src/directives/sticky-datatable-header.directive.ts, line 93 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/22#-Kwj4ZQzvc8NJ_lF2qRb:-Kwj4ZQzvc8NJ_lF2qRc:b-v8u1pl) ([raw file](https://github.com/kaltura/kaltura-ng/blob/c7a6a55f26820e1f0eab771353840e4824ad9d24/kaltura-primeng-ui/src/directives/sticky-datatable-header.directive.ts#L93)):*
> ```XML
>     private updateHeaderSize(){
>         if (this.isSticky) {
>             const tableWidth = this.elementRef.nativeElement.getBoundingClientRect()['right'] - this.elementRef.nativeElement.getBoundingClientRect()['left'];
> ```

consider calling `getBoundingClientRect` once like:
```
const {right, left} = this.elementRef.nativeElement.getBoundingClientRect();
const tableWidth = ...
```

---

*[kaltura-ui/src/area-blocker/area-blocker-message.ts, line 16 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/22#-Kwj4vpDJYgzfXzKFBig:-Kwj4vpDJYgzfXzKFBih:bkljkas) ([raw file](https://github.com/kaltura/kaltura-ng/blob/c7a6a55f26820e1f0eab771353840e4824ad9d24/kaltura-ui/src/area-blocker/area-blocker-message.ts#L16)):*
> ```XML
>     constructor(content : { title? : string, message : string, buttons : AreaBlockerMessageButton[]})
>     {
>         this.title = content.title || 'Error';
> ```

why? :( shlomit... bummer....

---

*[kaltura-ui/src/area-blocker/area-blocker.component.scss, line 14 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/22#-KwivCQQhB2T-7cp38Pp:-KwivCQQhB2T-7cp38Pq:b-1yzm1h) ([raw file](https://github.com/kaltura/kaltura-ng/blob/c7a6a55f26820e1f0eab771353840e4824ad9d24/kaltura-ui/src/area-blocker/area-blocker.component.scss#L14)):*
> ```SCSS
> 		top: 0;
> 		left: 0;
> 		display: flex;
> ```

KEA works with `kaltura-ui`and they support IE9 which means we cannot use `display:flex` here.

- move this part to the theme (also do the same in other places if any).
- make sure your other changes are backward compatible to what KEA is currently using

---

*[kaltura-ui/src/area-blocker/area-blocker.component.scss, line 91 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/22#-KwivnUYUiqtNN5ibjOZ:-KwivnUYUiqtNN5ibjO_:bgrzfpn) ([raw file](https://github.com/kaltura/kaltura-ng/blob/c7a6a55f26820e1f0eab771353840e4824ad9d24/kaltura-ui/src/area-blocker/area-blocker.component.scss#L91)):*
> ```SCSS
> 
> 		.kErrorMessageContainer {
> 			/*top: calc(50% - 100px);
> ```

same here need to support KEA project so those changes should be in the theme or part of a feature that is unlit by default and add the relevant classes once it is being used.

---

*[kaltura-ui/src/details-bar/details-bar.component.ts, line 36 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/22#-Kwj5VzGP4V-ejeUEOZu:-Kwj5VzGP4V-ejeUEOZv:b-n2cipi) ([raw file](https://github.com/kaltura/kaltura-ng/blob/c7a6a55f26820e1f0eab771353840e4824ad9d24/kaltura-ui/src/details-bar/details-bar.component.ts#L36)):*
> ```XML
>   private _itemsChangesSubscription: ISubscription;
> 
>   constructor(private _stickyScrollService: StickyScrollService) {
> ```

this is not good because people can use this component without using the sticky module (service). just use the `@HostListener` as it was 

---

*[kaltura-ui/src/popup-widget/popup-widget.component.ts, line 89 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/22#-Kwj5ZgpcnX4Q83-ttjf:-Kwj5ZgpcnX4Q83-ttjg:b-n2cipi) ([raw file](https://github.com/kaltura/kaltura-ng/blob/c7a6a55f26820e1f0eab771353840e4824ad9d24/kaltura-ui/src/popup-widget/popup-widget.component.ts#L89)):*
> ```XML
> 	public state$: Observable<popupStatus> = this._statechange.asObservable();
> 
>     constructor(public popup: ElementRef, private _stickyScrollService: StickyScrollService) {
> ```

this is not good because people can use this component without using the sticky module (service). just use the `@HostListener` as it was 

---

*[kaltura-ui/src/popup-widget/popup-widget.component.ts, line 154 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/22#-Kwj-_TfXvumXp3sND__:-Kwj-_TfXvumXp3sND_a:b-h1j1jc) ([raw file](https://github.com/kaltura/kaltura-ng/blob/c7a6a55f26820e1f0eab771353840e4824ad9d24/kaltura-ui/src/popup-widget/popup-widget.component.ts#L154)):*
> ```XML
> 	        if (this.preventPageScroll){
> 	        	this._saveOriginalScroll = window.getComputedStyle(document.body)["overflow-y"];
> 	        	document.body.style.overflowY = 'hidden';
> ```

did you tested the affect of nested popups that might override each other?

1 - show popup A -> hide
2 - show nested popup B -> hide
3 - hide popup B -> show (wrong behavior)

---

*[kaltura-ui/src/popup-widget/popup-widget.component.ts, line 220 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/22#-Kwj0-pN9pPtgjUA7liE:-Kwj0-pN9pPtgjUA7liF:b-bwjf5s) ([raw file](https://github.com/kaltura/kaltura-ng/blob/c7a6a55f26820e1f0eab771353840e4824ad9d24/kaltura-ui/src/popup-widget/popup-widget.component.ts#L220)):*
> ```XML
> 	{
> 		if (this.closeOnResize) {
> 			this._stickyScrollService.resizeStatus$.cancelOnDestroy(this).subscribe(
> ```

- you need to defer handling until to support consist resize
- it will lead to multiple invocations of the before close which 

---

*[kaltura-ui/src/sticky/directives/sticky.directive.ts, line 16 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/22#-Kwj0kektVJXfq18OiOx:-Kwj0kektVJXfq18OiOy:b-60newa) ([raw file](https://github.com/kaltura/kaltura-ng/blob/c7a6a55f26820e1f0eab771353840e4824ad9d24/kaltura-ui/src/sticky/directives/sticky.directive.ts#L16)):*
> ```XML
>     @Input('stickyClass') stickyClass: string;
>     @Input('stickyTop') stickyTop: number = 0;
>     @Input('stickyOffsetTop') stickyOffsetTop: number = 0;
> ```

it seems that you don't handle changes of this value by binding because you handle it once during `ngAfterContentInit`.

But this might not be relevant in the new changes

---

*[kaltura-ui/src/sticky/services/sticky-scroll.service.ts, line 20 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/22#-Kwj6U7guMSjNUYg9kp0:-Kwj6U7hnY_Dqv2XdwEd:bsev2zl) ([raw file](https://github.com/kaltura/kaltura-ng/blob/c7a6a55f26820e1f0eab771353840e4824ad9d24/kaltura-ui/src/sticky/services/sticky-scroll.service.ts#L20)):*
> ```XML
> 
> 	ngOnDestroy(){
> 		window.removeEventListener('scroll', this.manageScrollEvent.bind(this));
> ```

this is not the same function reference it will not remove the listener

---

*[kaltura-ui/src/tags/tags.component.ts, line 41 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/22#-Kwj75CaSr6LwzLdv2Lj:-Kwj75CaSr6LwzLdv2Lk:b-n2cipi) ([raw file](https://github.com/kaltura/kaltura-ng/blob/c7a6a55f26820e1f0eab771353840e4824ad9d24/kaltura-ui/src/tags/tags.component.ts#L41)):*
> ```XML
> 	public _scrollRightEnabled: boolean = true;
> 
>     constructor(private _stickyScrollService: StickyScrollService) {
> ```

this is not good because people can use this component without using the sticky module (service). just use the `@HostListener` as it was 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/22)*

**Comment by omridevk** [comment]
@esakal 
we support IE10+ :)

**Comment by esakal** [comment]
I though IE5... ) 

---

Review status: all files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/22#-:-Kwjhtzl8eTMIygz0ECz:bw6rlo9)*

**Comment by amirch1** [comment]
Review status: 18 of 21 files reviewed at latest revision, 12 unresolved discussions.

---

*[kaltura-ui/src/details-bar/details-bar.component.ts, line 36 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/22#-Kwj5VzGP4V-ejeUEOZu:-Kwn2mMHqOLQ8X3tHI_Z:b-896fix) ([raw file](https://github.com/kaltura/kaltura-ng/blob/c7a6a55f26820e1f0eab771353840e4824ad9d24/kaltura-ui/src/details-bar/details-bar.component.ts#L36)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

this is not good because people can use this component without using the sticky module (service). just use the `@HostListener` as it was 
</blockquote></details>

Done.

---

*[kaltura-ui/src/popup-widget/popup-widget.component.ts, line 89 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/22#-Kwj5ZgpcnX4Q83-ttjf:-Kwn2pFl5-qcDtZCNd9r:b-896fix) ([raw file](https://github.com/kaltura/kaltura-ng/blob/c7a6a55f26820e1f0eab771353840e4824ad9d24/kaltura-ui/src/popup-widget/popup-widget.component.ts#L89)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

this is not good because people can use this component without using the sticky module (service). just use the `@HostListener` as it was 
</blockquote></details>

Done.

---

*[kaltura-ui/src/sticky/directives/sticky.directive.ts, line 16 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/22#-Kwj0kektVJXfq18OiOx:-Kwn3Sedq3ZD1zyF371H:bot18gz) ([raw file](https://github.com/kaltura/kaltura-ng/blob/c7a6a55f26820e1f0eab771353840e4824ad9d24/kaltura-ui/src/sticky/directives/sticky.directive.ts#L16)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

it seems that you don't handle changes of this value by binding because you handle it once during `ngAfterContentInit`.

But this might not be relevant in the new changes
</blockquote></details>

will not matter with the new changes

---

*[kaltura-ui/src/sticky/services/sticky-scroll.service.ts, line 20 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/22#-Kwj6U7guMSjNUYg9kp0:-Kwn3lQhy-GoFrAxBngv:bv72wlf) ([raw file](https://github.com/kaltura/kaltura-ng/blob/c7a6a55f26820e1f0eab771353840e4824ad9d24/kaltura-ui/src/sticky/services/sticky-scroll.service.ts#L20)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

this is not the same function reference it will not remove the listener
</blockquote></details>

can you please provide the correct syntax for removal?

---

*[kaltura-ui/src/tags/tags.component.ts, line 41 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/22#-Kwj75CaSr6LwzLdv2Lj:-Kwn3sy7xUUJVaggdw3o:b-896fix) ([raw file](https://github.com/kaltura/kaltura-ng/blob/c7a6a55f26820e1f0eab771353840e4824ad9d24/kaltura-ui/src/tags/tags.component.ts#L41)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

this is not good because people can use this component without using the sticky module (service). just use the `@HostListener` as it was 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/22)*

**Comment by amirch1** [comment]
Review status: 13 of 21 files reviewed at latest revision, 12 unresolved discussions.

---

*[kaltura-primeng-ui/src/directives/sticky-datatable-header.directive.ts, line 6 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/22#-Kwj3WEhxnGD_GS9tBG2:-Kx1U282tYSKpyhSpUj-:b-896fix) ([raw file](https://github.com/kaltura/kaltura-ng/blob/c7a6a55f26820e1f0eab771353840e4824ad9d24/kaltura-primeng-ui/src/directives/sticky-datatable-header.directive.ts#L6)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

`k` prefix.... you can ignore if you don't have the power to change everywhere 
</blockquote></details>

Done.

---

*[kaltura-primeng-ui/src/directives/sticky-datatable-header.directive.ts, line 93 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/22#-Kwj4ZQzvc8NJ_lF2qRb:-Kx1V3elDszciPuk5zCq:b-896fix) ([raw file](https://github.com/kaltura/kaltura-ng/blob/c7a6a55f26820e1f0eab771353840e4824ad9d24/kaltura-primeng-ui/src/directives/sticky-datatable-header.directive.ts#L93)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

consider calling `getBoundingClientRect` once like:
```
const {right, left} = this.elementRef.nativeElement.getBoundingClientRect();
const tableWidth = ...
```
</blockquote></details>

Done.

---

*[kaltura-ui/src/area-blocker/area-blocker.component.scss, line 14 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/22#-KwivCQQhB2T-7cp38Pp:-Kx1Z6YmZBIGhRgOpryB:b-896fix) ([raw file](https://github.com/kaltura/kaltura-ng/blob/c7a6a55f26820e1f0eab771353840e4824ad9d24/kaltura-ui/src/area-blocker/area-blocker.component.scss#L14)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

KEA works with `kaltura-ui`and they support IE9 which means we cannot use `display:flex` here.

- move this part to the theme (also do the same in other places if any).
- make sure your other changes are backward compatible to what KEA is currently using
</blockquote></details>

Done.

---

*[kaltura-ui/src/area-blocker/area-blocker.component.scss, line 91 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/22#-KwivnUYUiqtNN5ibjOZ:-Kx1ZTA8ARXo656Zb72X:b-junr2u) ([raw file](https://github.com/kaltura/kaltura-ng/blob/c7a6a55f26820e1f0eab771353840e4824ad9d24/kaltura-ui/src/area-blocker/area-blocker.component.scss#L91)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

same here need to support KEA project so those changes should be in the theme or part of a feature that is unlit by default and add the relevant classes once it is being used.
</blockquote></details>

well - seems that the flex display was there from the beginning. we will need to refactor this.

---

*[kaltura-ui/src/sticky/services/sticky-scroll.service.ts, line 20 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/22#-Kwj6U7guMSjNUYg9kp0:-Kx1_bNG46TFzhaWzDQp:b-896fix) ([raw file](https://github.com/kaltura/kaltura-ng/blob/c7a6a55f26820e1f0eab771353840e4824ad9d24/kaltura-ui/src/sticky/services/sticky-scroll.service.ts#L20)):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

can you please provide the correct syntax for removal?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/22)*

**Comment by amirch1** [comment]
Review status: 13 of 21 files reviewed at latest revision, 12 unresolved discussions.

---

*[kaltura-ui/src/area-blocker/area-blocker-message.ts, line 16 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/22#-Kwj4vpDJYgzfXzKFBig:-Kx1jn_FtOgjZr6cm68v:b-896fix) ([raw file](https://github.com/kaltura/kaltura-ng/blob/c7a6a55f26820e1f0eab771353840e4824ad9d24/kaltura-ui/src/area-blocker/area-blocker-message.ts#L16)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

why? :( shlomit... bummer....
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/22)*

**Comment by amirch1** [comment]
Review status: 8 of 19 files reviewed at latest revision, 12 unresolved discussions.

---

*[kaltura-ui/src/popup-widget/popup-widget.component.ts, line 154 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/22#-Kwj-_TfXvumXp3sND__:-Kx29yrQw9E48V6t6gVV:btw59mp) ([raw file](https://github.com/kaltura/kaltura-ng/blob/c7a6a55f26820e1f0eab771353840e4824ad9d24/kaltura-ui/src/popup-widget/popup-widget.component.ts#L154)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

did you tested the affect of nested popups that might override each other?

1 - show popup A -> hide
2 - show nested popup B -> hide
3 - hide popup B -> show (wrong behavior)
</blockquote></details>

We will add this logic to the popup widget service if we encounter such use-case (currently no such use cases in KMC)

---

*[kaltura-ui/src/popup-widget/popup-widget.component.ts, line 220 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/22#-Kwj0-pN9pPtgjUA7liE:-Kx2A9PoqRTUVoZB1LzS:b-hmzc0e) ([raw file](https://github.com/kaltura/kaltura-ng/blob/c7a6a55f26820e1f0eab771353840e4824ad9d24/kaltura-ui/src/popup-widget/popup-widget.component.ts#L220)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

- you need to defer handling until to support consist resize
- it will lead to multiple invocations of the before close which 
</blockquote></details>

we will open a task to handle close on resize for popups if we cannot remove this option completely - I will discuss with Shlomit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/22)*

**Comment by esakal** [comment]
:lgtm:

---

Reviewed 11 of 13 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/22#-:-Kx2BjePEdzs-KRtTPd2:bnfp4nl)*

**Pull request merged**
