### PR TITLE
Added tooltips over custom data fields in metadata sections

### PR DESCRIPTION
**Pull request by benstov**
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kaltura-ng/37)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[kaltura-ui/src/dynamic-form/dynamic-form-item.component.html, line 5 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/37#-Kzs0S3qYABYhix_GmTJ:-Kzs0S3qYABYhix_GmTK:b-pr7acq) ([raw file](https://github.com/kaltura/kaltura-ng/blob/d4e398f5e0861db89ea4b2656b264d506086b0a9/kaltura-ui/src/dynamic-form/dynamic-form-item.component.html#L5)):*
> ```HTML
>     <ng-container  *ngIf="control.controlType === 'Group' && control.allowMultiple">
>             <div class="kMultiple" [formArrayName]="control.key">
>                 <span class="kGroupTitle" *ngIf="control.label" [kTooltip]="control.description">{{control.label}}</span>
> ```

you didn't handle long texts. remember to test edge cases...




---

*[kaltura-ui/src/dynamic-form/dynamic-form-item.component.html, line 31 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/37#-Kzs0XUu98MCgoN7i_7I:-Kzs0XUu98MCgoN7i_7J:b-j3csye) ([raw file](https://github.com/kaltura/kaltura-ng/blob/d4e398f5e0861db89ea4b2656b264d506086b0a9/kaltura-ui/src/dynamic-form/dynamic-form-item.component.html#L31)):*
> ```HTML
> 
>     <div class="kMultiple" *ngIf="control.controlType === 'Group' && !control.allowMultiple">
>         <span class="kGroupTitle" *ngIf="control.label" [kTooltip]="control.description">{{control.label}}</span>
> ```

you didn't handle long texts. remember to test edge cases...

---

*[kaltura-ui/src/dynamic-form/dynamic-form-item.component.html, line 41 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/37#-Kzs0Xwe0uS8VKHEBRI3:-Kzs0Xwe0uS8VKHEBRI4:b-j3csye) ([raw file](https://github.com/kaltura/kaltura-ng/blob/d4e398f5e0861db89ea4b2656b264d506086b0a9/kaltura-ui/src/dynamic-form/dynamic-form-item.component.html#L41)):*
> ```HTML
> 
>     <div class="kRow" *ngIf="control.controlType !== 'Group'">
>         <span class="kLabel" *ngIf="control.label" [kTooltip]="control.description">{{control.label}}</span>
> ```

you didn't handle long texts. remember to test edge cases...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/37)*

**Comment by benstov** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[kaltura-ui/src/dynamic-form/dynamic-form-item.component.html, line 5 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/37#-Kzs0S3qYABYhix_GmTJ:-Kzso6ZU5GxEXPimRTlk:b-896fix) ([raw file](https://github.com/kaltura/kaltura-ng/blob/d4e398f5e0861db89ea4b2656b264d506086b0a9/kaltura-ui/src/dynamic-form/dynamic-form-item.component.html#L5)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

you didn't handle long texts. remember to test edge cases...




</blockquote></details>

Done.

---

*[kaltura-ui/src/dynamic-form/dynamic-form-item.component.html, line 31 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/37#-Kzs0XUu98MCgoN7i_7I:-Kzso7o13Ihsg39XrRG-:b-896fix) ([raw file](https://github.com/kaltura/kaltura-ng/blob/d4e398f5e0861db89ea4b2656b264d506086b0a9/kaltura-ui/src/dynamic-form/dynamic-form-item.component.html#L31)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

you didn't handle long texts. remember to test edge cases...
</blockquote></details>

Done.

---

*[kaltura-ui/src/dynamic-form/dynamic-form-item.component.html, line 41 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng/37#-Kzs0Xwe0uS8VKHEBRI3:-Kzso947daEoIPY5vk-s:b-896fix) ([raw file](https://github.com/kaltura/kaltura-ng/blob/d4e398f5e0861db89ea4b2656b264d506086b0a9/kaltura-ui/src/dynamic-form/dynamic-form-item.component.html#L41)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

you didn't handle long texts. remember to test edge cases...
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/37)*

**Comment by esakal** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/37)*

**Comment by esakal** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng/37#-:-L-RwqQY8Vy1Q8ApniKu:bnfp4nl)*

**Pull request merged**
